# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'VideoList' do
  use_frameworks!
  pod 'Moya'
  pod 'Result'
  pod 'RxDataSources'
  pod 'Texture'
  pod 'Kingfisher'
  pod 'RxCocoa-Texture'
end
